version: '3.1'
services:
  spring:
    image: 'spring-shop.jar'
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'spring-shop'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
volumes:
  my-db: {}